<?xml version="1.0" encoding="gb2312"?>
<Project Name="map1306" Width="15" Height="9" CellSize="40" BackgroundSize="1" Background="11plus.png">
	<Cell Name="出生点" X="1" Y="1" />
	<Cell Name="冰块" X="2" Y="1" />
	<Cell Name="冰块" X="5" Y="1" />
	<Cell Name="冰块" X="7" Y="1" />
	<Cell Name="冰块" X="9" Y="1" />
	<Cell Name="冰块" X="11" Y="1" />
	<Cell Name="冰块" X="13" Y="1" />
	<Cell Name="冰块" X="1" Y="2" />
	<Cell Name="冰块" X="2" Y="2" />
	<Cell Name="冰块" X="4" Y="2" />
	<Cell Name="冰块" X="6" Y="2" />
	<Cell Name="冰块" X="8" Y="2" />
	<Cell Name="冰块" X="10" Y="2" />
	<Cell Name="冰块" X="13" Y="2" />
	<Cell Name="冰块" X="1" Y="3" />
	<Cell Name="冰块" X="3" Y="3" />
	<Cell Name="冰块" X="5" Y="3" />
	<Cell Name="冰块" X="7" Y="3" />
	<Cell Name="冰块" X="9" Y="3" />
	<Cell Name="冰块" X="11" Y="3" />
	<Cell Name="冰块" X="13" Y="3" />
	<Cell Name="冰块" X="1" Y="4" />
	<Cell Name="冰块" X="2" Y="4" />
	<Cell Name="冰块" X="4" Y="4" />
	<Cell Name="冰块" X="6" Y="4" />
	<Cell Name="冰块" X="8" Y="4" />
	<Cell Name="冰块" X="10" Y="4" />
	<Cell Name="冰块" X="13" Y="4" />
	<Cell Name="冰块" X="1" Y="5" />
	<Cell Name="冰块" X="3" Y="5" />
	<Cell Name="冰块" X="5" Y="5" />
	<Cell Name="房子" X="7" Y="5" />
	<Cell Name="冰块" X="9" Y="5" />
	<Cell Name="冰块" X="11" Y="5" />
	<Cell Name="冰块" X="13" Y="5" />
	<Cell Name="冰块" X="1" Y="6" />
	<Cell Name="冰块" X="2" Y="6" />
	<Cell Name="冰块" X="4" Y="6" />
	<Cell Name="冰块" X="6" Y="6" />
	<Cell Name="冰块" X="7" Y="6" />
	<Cell Name="冰块" X="8" Y="6" />
	<Cell Name="冰块" X="10" Y="6" />
	<Cell Name="冰块" X="13" Y="6" />
	<Cell Name="火墙" X="1" Y="7" arg0="30" arg1="40" arg2="5" />
	<Cell Name="冰块" X="3" Y="7" />
	<Cell Name="冰块" X="5" Y="7" />
	<Cell Name="冰块" X="7" Y="7" />
	<Cell Name="冰块" X="9" Y="7" />
	<Cell Name="冰块" X="11" Y="7" />
	<Cell Name="通关点-1" X="12" Y="7" />
	<Cell Name="冰块" X="13" Y="7" />
</Project>