<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3205" Width="13" Height="13" CellSize="40" BackgroundSize="2" Background="_t.png">
	<Cell Name="出生点" X="1" Y="1" />
	<Cell Name="箱子2" X="3" Y="1" />
	<Cell Name="瘟疫花" X="4" Y="1" />
	<Cell Name="墙2" X="5" Y="1" />
	<Cell Name="瘟疫花" X="6" Y="1" />
	<Cell Name="墙2" X="7" Y="1" />
	<Cell Name="箱子2" X="8" Y="1" />
	<Cell Name="瘟疫花" X="9" Y="1" />
	<Cell Name="出生点" X="11" Y="1" />
	<Cell Name="瘟疫花" X="2" Y="2" />
	<Cell Name="十字架" X="3" Y="2" />
	<Cell Name="瘟疫花" X="5" Y="2" />
	<Cell Name="瘟疫花" X="7" Y="2" />
	<Cell Name="十字架" X="9" Y="2" />
	<Cell Name="瘟疫花" X="10" Y="2" />
	<Cell Name="瘟疫花" X="1" Y="3" />
	<Cell Name="墙2" X="2" Y="3" />
	<Cell Name="瘟疫花" X="3" Y="3" />
	<Cell Name="箱子2" X="4" Y="3" />
	<Cell Name="箱子2" X="8" Y="3" />
	<Cell Name="瘟疫花" X="9" Y="3" />
	<Cell Name="墙2" X="10" Y="3" />
	<Cell Name="瘟疫花" X="11" Y="3" />
	<Cell Name="瘟疫花" X="5" Y="4" />
	<Cell Name="瘟疫花" X="7" Y="4" />
	<Cell Name="箱子2" X="10" Y="4" />
	<Cell Name="墙2" X="1" Y="5" />
	<Cell Name="瘟疫花" X="3" Y="5" />
	<Cell Name="箱子2" X="4" Y="5" />
	<Cell Name="十字架" X="5" Y="5" />
	<Cell Name="瘟疫花" X="6" Y="5" />
	<Cell Name="十字架" X="7" Y="5" />
	<Cell Name="箱子2" X="9" Y="5" />
	<Cell Name="墙2" X="11" Y="5" />
	<Cell Name="瘟疫花" X="1" Y="6" />
	<Cell Name="瘟疫花" X="2" Y="6" />
	<Cell Name="瘟疫花" X="4" Y="6" />
	<Cell Name="箱子2" X="6" Y="6" />
	<Cell Name="瘟疫花" X="8" Y="6" />
	<Cell Name="瘟疫花" X="10" Y="6" />
	<Cell Name="瘟疫花" X="11" Y="6" />
	<Cell Name="墙2" X="1" Y="7" />
	<Cell Name="箱子2" X="3" Y="7" />
	<Cell Name="墙2" X="5" Y="7" />
	<Cell Name="瘟疫花" X="6" Y="7" />
	<Cell Name="墙2" X="7" Y="7" />
	<Cell Name="瘟疫花" X="9" Y="7" />
	<Cell Name="墙2" X="11" Y="7" />
	<Cell Name="箱子2" X="2" Y="8" />
	<Cell Name="箱子2" X="4" Y="8" />
	<Cell Name="瘟疫花" X="5" Y="8" />
	<Cell Name="瘟疫花" X="7" Y="8" />
	<Cell Name="瘟疫花" X="8" Y="8" />
	<Cell Name="箱子2" X="10" Y="8" />
	<Cell Name="瘟疫花" X="1" Y="9" />
	<Cell Name="瘟疫花" X="3" Y="9" />
	<Cell Name="十字架" X="5" Y="9" />
	<Cell Name="箱子2" X="8" Y="9" />
	<Cell Name="瘟疫花" X="9" Y="9" />
	<Cell Name="墙2" X="10" Y="9" />
	<Cell Name="瘟疫花" X="11" Y="9" />
	<Cell Name="墙2" X="1" Y="10" />
	<Cell Name="出生点" X="2" Y="10" />
	<Cell Name="瘟疫花" X="5" Y="10" />
	<Cell Name="瘟疫花" X="7" Y="10" />
	<Cell Name="瘟疫花" X="10" Y="10" />
	<Cell Name="墙2" X="2" Y="11" />
	<Cell Name="箱子2" X="3" Y="11" />
	<Cell Name="瘟疫花" X="4" Y="11" />
	<Cell Name="墙2" X="5" Y="11" />
	<Cell Name="瘟疫花" X="6" Y="11" />
	<Cell Name="墙2" X="7" Y="11" />
	<Cell Name="箱子2" X="8" Y="11" />
	<Cell Name="瘟疫花" X="9" Y="11" />
	<Cell Name="出生点" X="11" Y="11" />
</Project>