<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3103" Width="13" Height="11" CellSize="40" BackgroundSize="2" Background="_t.png">
	<Cell Name="出生点" X="1" Y="1" />
	<Cell Name="蘑菇" X="3" Y="1" />
	<Cell Name="丛林图腾2" X="4" Y="1" />
	<Cell Name="蘑菇" X="5" Y="1" />
	<Cell Name="蘑菇" X="7" Y="1" />
	<Cell Name="丛林图腾2" X="8" Y="1" />
	<Cell Name="蘑菇" X="9" Y="1" />
	<Cell Name="出生点" X="11" Y="1" />
	<Cell Name="丛林图腾2" X="2" Y="2" />
	<Cell Name="蘑菇" X="3" Y="2" />
	<Cell Name="树" X="5" Y="2" />
	<Cell Name="树" X="7" Y="2" />
	<Cell Name="蘑菇" X="9" Y="2" />
	<Cell Name="丛林图腾2" X="10" Y="2" />
	<Cell Name="蘑菇" X="1" Y="3" />
	<Cell Name="蘑菇" X="2" Y="3" />
	<Cell Name="蘑菇" X="4" Y="3" />
	<Cell Name="蘑菇" X="6" Y="3" />
	<Cell Name="蘑菇" X="7" Y="3" />
	<Cell Name="丛林图腾2" X="8" Y="3" />
	<Cell Name="树" X="10" Y="3" />
	<Cell Name="蘑菇" X="11" Y="3" />
	<Cell Name="丛林图腾2" X="1" Y="4" />
	<Cell Name="树" X="3" Y="4" />
	<Cell Name="蘑菇" X="4" Y="4" />
	<Cell Name="丛林图腾2" X="5" Y="4" />
	<Cell Name="树" X="7" Y="4" />
	<Cell Name="蘑菇" X="8" Y="4" />
	<Cell Name="树" X="9" Y="4" />
	<Cell Name="蘑菇" X="10" Y="4" />
	<Cell Name="蘑菇" X="11" Y="4" />
	<Cell Name="蘑菇" X="1" Y="5" />
	<Cell Name="树" X="2" Y="5" />
	<Cell Name="蘑菇" X="5" Y="5" />
	<Cell Name="蘑菇" X="7" Y="5" />
	<Cell Name="蘑菇" X="9" Y="5" />
	<Cell Name="丛林图腾2" X="11" Y="5" />
	<Cell Name="丛林图腾2" X="1" Y="6" />
	<Cell Name="蘑菇" X="2" Y="6" />
	<Cell Name="树" X="3" Y="6" />
	<Cell Name="树" X="5" Y="6" />
	<Cell Name="蘑菇" X="6" Y="6" />
	<Cell Name="丛林图腾2" X="7" Y="6" />
	<Cell Name="蘑菇" X="8" Y="6" />
	<Cell Name="树" X="9" Y="6" />
	<Cell Name="蘑菇" X="11" Y="6" />
	<Cell Name="丛林图腾2" X="3" Y="7" />
	<Cell Name="丛林图腾2" X="4" Y="7" />
	<Cell Name="蘑菇" X="5" Y="7" />
	<Cell Name="蘑菇" X="7" Y="7" />
	<Cell Name="蘑菇" X="10" Y="7" />
	<Cell Name="蘑菇" X="11" Y="7" />
	<Cell Name="丛林图腾2" X="1" Y="8" />
	<Cell Name="出生点" X="2" Y="8" />
	<Cell Name="树" X="5" Y="8" />
	<Cell Name="树" X="7" Y="8" />
	<Cell Name="蘑菇" X="8" Y="8" />
	<Cell Name="蘑菇" X="9" Y="8" />
	<Cell Name="丛林图腾2" X="10" Y="8" />
	<Cell Name="丛林图腾2" X="2" Y="9" />
	<Cell Name="蘑菇" X="3" Y="9" />
	<Cell Name="丛林图腾2" X="4" Y="9" />
	<Cell Name="蘑菇" X="5" Y="9" />
	<Cell Name="蘑菇" X="6" Y="9" />
	<Cell Name="蘑菇" X="7" Y="9" />
	<Cell Name="丛林图腾2" X="8" Y="9" />
	<Cell Name="蘑菇" X="9" Y="9" />
	<Cell Name="出生点" X="11" Y="9" />
</Project>