<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3101" Width="13" Height="9" CellSize="40" BackgroundSize="3" Background="ditu.png">
	<Cell Name="出生点" X="1" Y="1" />
	<Cell Name="樱桃树" X="3" Y="1" />
	<Cell Name="樱桃树" X="4" Y="1" />
	<Cell Name="樱桃树" X="5" Y="1" />
	<Cell Name="樱桃树" X="6" Y="1" />
	<Cell Name="樱桃树" X="8" Y="1" />
	<Cell Name="樱桃树" X="9" Y="1" />
	<Cell Name="出生点" X="11" Y="1" />
	<Cell Name="木桩2" X="1" Y="2" />
	<Cell Name="木桩2" X="3" Y="2" />
	<Cell Name="木桩2" X="5" Y="2" />
	<Cell Name="樱桃树" X="6" Y="2" />
	<Cell Name="木桩2" X="7" Y="2" />
	<Cell Name="樱桃树" X="8" Y="2" />
	<Cell Name="木桩2" X="9" Y="2" />
	<Cell Name="木桩2" X="11" Y="2" />
	<Cell Name="樱桃树" X="1" Y="3" />
	<Cell Name="樱桃树" X="2" Y="3" />
	<Cell Name="木桩2" X="3" Y="3" />
	<Cell Name="樱桃树" X="4" Y="3" />
	<Cell Name="樱桃树" X="6" Y="3" />
	<Cell Name="木桩2" X="7" Y="3" />
	<Cell Name="樱桃树" X="9" Y="3" />
	<Cell Name="樱桃树" X="10" Y="3" />
	<Cell Name="木桩2" X="11" Y="3" />
	<Cell Name="樱桃树" X="1" Y="4" />
	<Cell Name="樱桃树" X="2" Y="4" />
	<Cell Name="樱桃树" X="4" Y="4" />
	<Cell Name="樱桃树" X="5" Y="4" />
	<Cell Name="樱桃树" X="6" Y="4" />
	<Cell Name="樱桃树" X="8" Y="4" />
	<Cell Name="樱桃树" X="10" Y="4" />
	<Cell Name="樱桃树" X="11" Y="4" />
	<Cell Name="木桩" X="3" Y="5" />
	<Cell Name="木桩2" X="5" Y="5" />
	<Cell Name="樱桃树" X="6" Y="5" />
	<Cell Name="樱桃树" X="7" Y="5" />
	<Cell Name="樱桃树" X="8" Y="5" />
	<Cell Name="木桩2" X="9" Y="5" />
	<Cell Name="樱桃树" X="10" Y="5" />
	<Cell Name="樱桃树" X="11" Y="5" />
	<Cell Name="木桩2" X="1" Y="6" />
	<Cell Name="出生点" X="2" Y="6" />
	<Cell Name="樱桃树" X="4" Y="6" />
	<Cell Name="木桩2" X="5" Y="6" />
	<Cell Name="木桩2" X="7" Y="6" />
	<Cell Name="樱桃树" X="8" Y="6" />
	<Cell Name="木桩2" X="9" Y="6" />
	<Cell Name="木桩2" X="11" Y="6" />
	<Cell Name="木桩" X="2" Y="7" />
	<Cell Name="樱桃树" X="3" Y="7" />
	<Cell Name="樱桃树" X="4" Y="7" />
	<Cell Name="樱桃树" X="6" Y="7" />
	<Cell Name="樱桃树" X="8" Y="7" />
	<Cell Name="樱桃树" X="9" Y="7" />
	<Cell Name="出生点" X="11" Y="7" />
</Project>