<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3302" Width="13" Height="11" CellSize="40" BackgroundSize="2" Background="_t.png">
	<Cell Name="出生点" X="1" Y="1" />
	<Cell Name="雪块" X="3" Y="1" />
	<Cell Name="雪块" X="5" Y="1" />
	<Cell Name="雪块" X="7" Y="1" />
	<Cell Name="雪块" X="9" Y="1" />
	<Cell Name="出生点" X="11" Y="1" />
	<Cell Name="冰雕" X="2" Y="2" />
	<Cell Name="冰块" X="4" Y="2" />
	<Cell Name="冰雕" X="6" Y="2" />
	<Cell Name="冰块" X="8" Y="2" />
	<Cell Name="冰雕" X="10" Y="2" />
	<Cell Name="雪块" X="1" Y="3" />
	<Cell Name="雪块" X="3" Y="3" />
	<Cell Name="雪块" X="5" Y="3" />
	<Cell Name="雪块" X="6" Y="3" />
	<Cell Name="雪块" X="7" Y="3" />
	<Cell Name="雪块" X="9" Y="3" />
	<Cell Name="雪块" X="11" Y="3" />
	<Cell Name="雪块" X="2" Y="4" />
	<Cell Name="雪块" X="3" Y="4" />
	<Cell Name="冰雕" X="4" Y="4" />
	<Cell Name="冰块" X="6" Y="4" />
	<Cell Name="冰雕" X="8" Y="4" />
	<Cell Name="雪块" X="9" Y="4" />
	<Cell Name="冰雕" X="1" Y="5" />
	<Cell Name="雪块" X="3" Y="5" />
	<Cell Name="雪块" X="5" Y="5" />
	<Cell Name="雪块" X="7" Y="5" />
	<Cell Name="雪块" X="8" Y="5" />
	<Cell Name="雪块" X="10" Y="5" />
	<Cell Name="冰雕" X="11" Y="5" />
	<Cell Name="雪块" X="1" Y="6" />
	<Cell Name="雪块" X="2" Y="6" />
	<Cell Name="冰雕" X="4" Y="6" />
	<Cell Name="冰块" X="6" Y="6" />
	<Cell Name="冰雕" X="8" Y="6" />
	<Cell Name="雪块" X="9" Y="6" />
	<Cell Name="雪块" X="11" Y="6" />
	<Cell Name="雪块" X="1" Y="7" />
	<Cell Name="冰雕" X="3" Y="7" />
	<Cell Name="雪块" X="5" Y="7" />
	<Cell Name="雪块" X="6" Y="7" />
	<Cell Name="雪块" X="7" Y="7" />
	<Cell Name="雪块" X="9" Y="7" />
	<Cell Name="雪块" X="11" Y="7" />
	<Cell Name="冰雕" X="1" Y="8" />
	<Cell Name="出生点" X="2" Y="8" />
	<Cell Name="冰块" X="4" Y="8" />
	<Cell Name="冰雕" X="6" Y="8" />
	<Cell Name="雪块" X="7" Y="8" />
	<Cell Name="冰块" X="8" Y="8" />
	<Cell Name="冰雕" X="10" Y="8" />
	<Cell Name="冰雕" X="2" Y="9" />
	<Cell Name="雪块" X="3" Y="9" />
	<Cell Name="雪块" X="5" Y="9" />
	<Cell Name="雪块" X="7" Y="9" />
	<Cell Name="雪块" X="9" Y="9" />
	<Cell Name="出生点" X="11" Y="9" />
</Project>