<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3304" Width="13" Height="13" CellSize="40" BackgroundSize="2" Background="_t.png">
	<Cell Name="房子" X="2" Y="1" />
	<Cell Name="贝壳" X="3" Y="1" />
	<Cell Name="贝壳" X="4" Y="1" />
	<Cell Name="出生点" X="6" Y="1" />
	<Cell Name="贝壳" X="8" Y="1" />
	<Cell Name="贝壳" X="9" Y="1" />
	<Cell Name="房子" X="10" Y="1" />
	<Cell Name="房子" X="1" Y="2" />
	<Cell Name="贝壳" X="4" Y="2" />
	<Cell Name="贝壳" X="5" Y="2" />
	<Cell Name="贝壳" X="7" Y="2" />
	<Cell Name="贝壳" X="8" Y="2" />
	<Cell Name="房子" X="11" Y="2" />
	<Cell Name="贝壳" X="1" Y="3" />
	<Cell Name="贝壳" X="3" Y="3" />
	<Cell Name="贝壳" X="4" Y="3" />
	<Cell Name="贝壳" X="5" Y="3" />
	<Cell Name="房子" X="6" Y="3" />
	<Cell Name="贝壳" X="7" Y="3" />
	<Cell Name="贝壳" X="8" Y="3" />
	<Cell Name="贝壳" X="9" Y="3" />
	<Cell Name="贝壳" X="11" Y="3" />
	<Cell Name="贝壳" X="1" Y="4" />
	<Cell Name="贝壳" X="2" Y="4" />
	<Cell Name="贝壳" X="3" Y="4" />
	<Cell Name="贝壳" X="5" Y="4" />
	<Cell Name="贝壳" X="6" Y="4" />
	<Cell Name="贝壳" X="7" Y="4" />
	<Cell Name="贝壳" X="9" Y="4" />
	<Cell Name="贝壳" X="10" Y="4" />
	<Cell Name="贝壳" X="11" Y="4" />
	<Cell Name="贝壳" X="2" Y="5" />
	<Cell Name="贝壳" X="3" Y="5" />
	<Cell Name="贝壳" X="4" Y="5" />
	<Cell Name="贝壳" X="5" Y="5" />
	<Cell Name="贝壳" X="6" Y="5" />
	<Cell Name="贝壳" X="7" Y="5" />
	<Cell Name="贝壳" X="8" Y="5" />
	<Cell Name="贝壳" X="9" Y="5" />
	<Cell Name="贝壳" X="10" Y="5" />
	<Cell Name="出生点" X="1" Y="6" />
	<Cell Name="房子" X="3" Y="6" />
	<Cell Name="贝壳" X="4" Y="6" />
	<Cell Name="贝壳" X="5" Y="6" />
	<Cell Name="房子" X="6" Y="6" />
	<Cell Name="贝壳" X="7" Y="6" />
	<Cell Name="贝壳" X="8" Y="6" />
	<Cell Name="房子" X="9" Y="6" />
	<Cell Name="出生点" X="11" Y="6" />
	<Cell Name="贝壳" X="2" Y="7" />
	<Cell Name="贝壳" X="3" Y="7" />
	<Cell Name="贝壳" X="4" Y="7" />
	<Cell Name="贝壳" X="5" Y="7" />
	<Cell Name="贝壳" X="6" Y="7" />
	<Cell Name="贝壳" X="7" Y="7" />
	<Cell Name="贝壳" X="8" Y="7" />
	<Cell Name="贝壳" X="9" Y="7" />
	<Cell Name="贝壳" X="10" Y="7" />
	<Cell Name="贝壳" X="1" Y="8" />
	<Cell Name="贝壳" X="2" Y="8" />
	<Cell Name="贝壳" X="3" Y="8" />
	<Cell Name="贝壳" X="5" Y="8" />
	<Cell Name="贝壳" X="6" Y="8" />
	<Cell Name="贝壳" X="7" Y="8" />
	<Cell Name="贝壳" X="9" Y="8" />
	<Cell Name="贝壳" X="10" Y="8" />
	<Cell Name="贝壳" X="11" Y="8" />
	<Cell Name="贝壳" X="1" Y="9" />
	<Cell Name="贝壳" X="3" Y="9" />
	<Cell Name="贝壳" X="4" Y="9" />
	<Cell Name="贝壳" X="5" Y="9" />
	<Cell Name="房子" X="6" Y="9" />
	<Cell Name="贝壳" X="7" Y="9" />
	<Cell Name="贝壳" X="8" Y="9" />
	<Cell Name="贝壳" X="9" Y="9" />
	<Cell Name="贝壳" X="11" Y="9" />
	<Cell Name="房子" X="1" Y="10" />
	<Cell Name="贝壳" X="4" Y="10" />
	<Cell Name="贝壳" X="5" Y="10" />
	<Cell Name="贝壳" X="7" Y="10" />
	<Cell Name="贝壳" X="8" Y="10" />
	<Cell Name="房子" X="11" Y="10" />
	<Cell Name="房子" X="2" Y="11" />
	<Cell Name="贝壳" X="3" Y="11" />
	<Cell Name="贝壳" X="4" Y="11" />
	<Cell Name="出生点" X="6" Y="11" />
	<Cell Name="贝壳" X="8" Y="11" />
	<Cell Name="贝壳" X="9" Y="11" />
	<Cell Name="房子" X="10" Y="11" />
</Project>