<?xml version="1.0" encoding="gb2312"?>
<Project Name="map3303" Width="13" Height="13" CellSize="40" BackgroundSize="2" Background="_t.png">
	<Cell Name="雪灌木" X="1" Y="1" />
	<Cell Name="雪灌木" X="2" Y="1" />
	<Cell Name="雪灌木" X="4" Y="1" />
	<Cell Name="出生点" X="6" Y="1" />
	<Cell Name="雪灌木" X="8" Y="1" />
	<Cell Name="雪灌木" X="10" Y="1" />
	<Cell Name="雪灌木" X="1" Y="2" />
	<Cell Name="雪人" X="3" Y="2" />
	<Cell Name="雪灌木" X="4" Y="2" />
	<Cell Name="雪人" X="6" Y="2" />
	<Cell Name="雪灌木" X="8" Y="2" />
	<Cell Name="冰墙" X="9" Y="2" />
	<Cell Name="雪灌木" X="10" Y="2" />
	<Cell Name="雪灌木" X="11" Y="2" />
	<Cell Name="冰墙" X="2" Y="3" />
	<Cell Name="雪灌木" X="3" Y="3" />
	<Cell Name="雪灌木" X="4" Y="3" />
	<Cell Name="雪灌木" X="5" Y="3" />
	<Cell Name="雪灌木" X="7" Y="3" />
	<Cell Name="雪灌木" X="9" Y="3" />
	<Cell Name="冰墙" X="10" Y="3" />
	<Cell Name="雪灌木" X="1" Y="4" />
	<Cell Name="雪灌木" X="2" Y="4" />
	<Cell Name="雪灌木" X="3" Y="4" />
	<Cell Name="雪人" X="4" Y="4" />
	<Cell Name="冰墙" X="6" Y="4" />
	<Cell Name="雪人" X="8" Y="4" />
	<Cell Name="雪灌木" X="9" Y="4" />
	<Cell Name="雪灌木" X="10" Y="4" />
	<Cell Name="雪灌木" X="11" Y="4" />
	<Cell Name="雪灌木" X="3" Y="5" />
	<Cell Name="雪灌木" X="4" Y="5" />
	<Cell Name="雪灌木" X="5" Y="5" />
	<Cell Name="雪灌木" X="6" Y="5" />
	<Cell Name="雪灌木" X="7" Y="5" />
	<Cell Name="雪灌木" X="9" Y="5" />
	<Cell Name="出生点" X="1" Y="6" />
	<Cell Name="雪人" X="2" Y="6" />
	<Cell Name="雪灌木" X="3" Y="6" />
	<Cell Name="冰墙" X="4" Y="6" />
	<Cell Name="雪灌木" X="5" Y="6" />
	<Cell Name="冰墙" X="6" Y="6" />
	<Cell Name="雪灌木" X="7" Y="6" />
	<Cell Name="雪人" X="8" Y="6" />
	<Cell Name="雪灌木" X="9" Y="6" />
	<Cell Name="雪人" X="10" Y="6" />
	<Cell Name="出生点" X="11" Y="6" />
	<Cell Name="雪灌木" X="3" Y="7" />
	<Cell Name="雪灌木" X="5" Y="7" />
	<Cell Name="雪灌木" X="6" Y="7" />
	<Cell Name="雪灌木" X="7" Y="7" />
	<Cell Name="雪灌木" X="9" Y="7" />
	<Cell Name="雪灌木" X="1" Y="8" />
	<Cell Name="雪灌木" X="2" Y="8" />
	<Cell Name="雪灌木" X="3" Y="8" />
	<Cell Name="雪人" X="4" Y="8" />
	<Cell Name="冰墙" X="6" Y="8" />
	<Cell Name="雪灌木" X="7" Y="8" />
	<Cell Name="冰墙" X="8" Y="8" />
	<Cell Name="雪灌木" X="9" Y="8" />
	<Cell Name="雪灌木" X="10" Y="8" />
	<Cell Name="雪灌木" X="11" Y="8" />
	<Cell Name="雪灌木" X="2" Y="9" />
	<Cell Name="雪灌木" X="4" Y="9" />
	<Cell Name="雪灌木" X="5" Y="9" />
	<Cell Name="雪灌木" X="6" Y="9" />
	<Cell Name="雪灌木" X="7" Y="9" />
	<Cell Name="雪灌木" X="8" Y="9" />
	<Cell Name="冰墙" X="10" Y="9" />
	<Cell Name="冰墙" X="1" Y="10" />
	<Cell Name="雪灌木" X="3" Y="10" />
	<Cell Name="雪灌木" X="4" Y="10" />
	<Cell Name="雪人" X="6" Y="10" />
	<Cell Name="雪灌木" X="8" Y="10" />
	<Cell Name="雪人" X="9" Y="10" />
	<Cell Name="雪灌木" X="10" Y="10" />
	<Cell Name="雪灌木" X="11" Y="10" />
	<Cell Name="冰墙" X="2" Y="11" />
	<Cell Name="雪灌木" X="4" Y="11" />
	<Cell Name="出生点" X="6" Y="11" />
	<Cell Name="雪灌木" X="8" Y="11" />
	<Cell Name="雪灌木" X="10" Y="11" />
</Project>